numero = int(input('Valor para sacar entre 10 e 600: '))
cem = int(numero / 100)
numero = numero - (cem*100)
cinquenta = int(numero/50)
numero = numero - (cinquenta*50)
dez = int(numero/10)
numero = numero - (dez*10)
cinco = int(numero/5)
numero = numero - (cinco*5) 
um = numero
print(f'{cem} notas de R$ 100')
print(f'{cinquenta} notas de R$ 50')
print(f'{dez} notas de R$ 10')
print(f'{cinco} notas de R$ 5')
print(f'{um} notas de R$ 1')
